
front:
  build: images/nginx
  ports:
    - "80:80"
#    - "9000:9000"
  links:
    - mysql:mysql
  volumes:
    - .:/var/www/gds
    - sites:/etc/nginx/sites-enabled
  extra_hosts:
      gds.local: 127.0.0.1

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_PASS: password
