version: '2'
services:
  front:
    build: images/nginx
    ports:
      - "80:80"
  #    - "9000:9000"
    links:
      - mysql:mysql
    volumes:
      - .:/var/www/gds
      - ./sites:/etc/nginx/sites-enabled
      - /var/www/gds/app/cache
      - /var/www/gds/app/logs
    extra_hosts:
        gds.local: 127.0.0.1
#    command: chown -R 1000 /var/www/gds/app/logs

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASS: password
      MYSQL_ROOT_PASSWORD: password

