security:

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2a$12$K8tfuOCZ12cuNtVBZyBxPO.EooGFY6k8rxnKPP77C3pAf3ZlZ453.
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
